
language: minimal

sudo: required

services:
  - docker

jobs:
  include:
    - script: |
        docker run -it -v ${TRAVIS_BUILD_DIR}:/repo.git -w /repo.git chapel/chapel:1.19.0 /bin/bash -c '
        cd test
        start_test'
   
